<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/iam/policy/v1alpha1/policy.proto

namespace Cbws\IAM\Policy\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Associates `members` with a `role`.
 *
 * Generated from protobuf message <code>cbws.iam.policy.v1alpha1.Binding</code>
 */
class Binding extends \Google\Protobuf\Internal\Message
{
    /**
     * Role that is assigned to `members`.
     * For example, `roles/viewer`, `roles/editor`, or `roles/owner`.
     *
     * Generated from protobuf field <code>string role = 1;</code>
     */
    protected $role = '';
    /**
     * Generated from protobuf field <code>string description = 3;</code>
     */
    protected $description = '';
    /**
     * Specifies the identities requesting access for a Cloud Platform resource.
     * `members` can have the following values:
     * * `anonymous`: A special identifier that represents anyone who is
     *    on the internet
     * * `allUsers`: A special identifier that represents anyone who is
     *    authenticated with a Cloudbear account or a service account.
     * * `user:{emailid}`: An email address that represents a specific Google
     *    account. For example, `alice&#64;example.com` .
     * * `serviceAccount:{emailid}`: An email address that represents a service
     *    account. For example, `my-other-app&#64;appspot.gserviceaccount.com`.
     * * `group:{emailid}`: An email address that represents a Google group.
     *    For example, `admins&#64;example.com`.
     * * `principal:{id}`: Identifier of the specific principal, can be used if
     *    access to either the user, serviceAccount or group is not available and
     *    only the principal id is known. This member type is only available when
     *    setting a IAM policy and is not returned when getting a IAM policy.
     *
     * Generated from protobuf field <code>repeated string members = 2;</code>
     */
    private $members;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $role
     *           Role that is assigned to `members`.
     *           For example, `roles/viewer`, `roles/editor`, or `roles/owner`.
     *     @type string $description
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $members
     *           Specifies the identities requesting access for a Cloud Platform resource.
     *           `members` can have the following values:
     *           * `anonymous`: A special identifier that represents anyone who is
     *              on the internet
     *           * `allUsers`: A special identifier that represents anyone who is
     *              authenticated with a Cloudbear account or a service account.
     *           * `user:{emailid}`: An email address that represents a specific Google
     *              account. For example, `alice&#64;example.com` .
     *           * `serviceAccount:{emailid}`: An email address that represents a service
     *              account. For example, `my-other-app&#64;appspot.gserviceaccount.com`.
     *           * `group:{emailid}`: An email address that represents a Google group.
     *              For example, `admins&#64;example.com`.
     *           * `principal:{id}`: Identifier of the specific principal, can be used if
     *              access to either the user, serviceAccount or group is not available and
     *              only the principal id is known. This member type is only available when
     *              setting a IAM policy and is not returned when getting a IAM policy.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\IAM\Policy\GRPC\V1alpha1\Metadata\Policy::initOnce();
        parent::__construct($data);
    }

    /**
     * Role that is assigned to `members`.
     * For example, `roles/viewer`, `roles/editor`, or `roles/owner`.
     *
     * Generated from protobuf field <code>string role = 1;</code>
     * @return string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Role that is assigned to `members`.
     * For example, `roles/viewer`, `roles/editor`, or `roles/owner`.
     *
     * Generated from protobuf field <code>string role = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkString($var, True);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Specifies the identities requesting access for a Cloud Platform resource.
     * `members` can have the following values:
     * * `anonymous`: A special identifier that represents anyone who is
     *    on the internet
     * * `allUsers`: A special identifier that represents anyone who is
     *    authenticated with a Cloudbear account or a service account.
     * * `user:{emailid}`: An email address that represents a specific Google
     *    account. For example, `alice&#64;example.com` .
     * * `serviceAccount:{emailid}`: An email address that represents a service
     *    account. For example, `my-other-app&#64;appspot.gserviceaccount.com`.
     * * `group:{emailid}`: An email address that represents a Google group.
     *    For example, `admins&#64;example.com`.
     * * `principal:{id}`: Identifier of the specific principal, can be used if
     *    access to either the user, serviceAccount or group is not available and
     *    only the principal id is known. This member type is only available when
     *    setting a IAM policy and is not returned when getting a IAM policy.
     *
     * Generated from protobuf field <code>repeated string members = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMembers()
    {
        return $this->members;
    }

    /**
     * Specifies the identities requesting access for a Cloud Platform resource.
     * `members` can have the following values:
     * * `anonymous`: A special identifier that represents anyone who is
     *    on the internet
     * * `allUsers`: A special identifier that represents anyone who is
     *    authenticated with a Cloudbear account or a service account.
     * * `user:{emailid}`: An email address that represents a specific Google
     *    account. For example, `alice&#64;example.com` .
     * * `serviceAccount:{emailid}`: An email address that represents a service
     *    account. For example, `my-other-app&#64;appspot.gserviceaccount.com`.
     * * `group:{emailid}`: An email address that represents a Google group.
     *    For example, `admins&#64;example.com`.
     * * `principal:{id}`: Identifier of the specific principal, can be used if
     *    access to either the user, serviceAccount or group is not available and
     *    only the principal id is known. This member type is only available when
     *    setting a IAM policy and is not returned when getting a IAM policy.
     *
     * Generated from protobuf field <code>repeated string members = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMembers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->members = $arr;

        return $this;
    }

}

