<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/iam/policy/v1alpha1/request_response.proto

namespace Cbws\IAM\Policy\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.iam.policy.v1alpha1.TestPermissionsResponse</code>
 */
class TestPermissionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * A subset of `TestPermissionsRequest.permissions` that the caller is
     * allowed.
     *
     * Generated from protobuf field <code>repeated string permissions = 1;</code>
     */
    private $permissions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $permissions
     *           A subset of `TestPermissionsRequest.permissions` that the caller is
     *           allowed.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\Policy\IAM\GRPC\V1alpha1\Metadata\RequestResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * A subset of `TestPermissionsRequest.permissions` that the caller is
     * allowed.
     *
     * Generated from protobuf field <code>repeated string permissions = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPermissions()
    {
        return $this->permissions;
    }

    /**
     * A subset of `TestPermissionsRequest.permissions` that the caller is
     * allowed.
     *
     * Generated from protobuf field <code>repeated string permissions = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPermissions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->permissions = $arr;

        return $this;
    }

}

