<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/longrunning/operations.proto

namespace Cbws\Grpc\Longrunning;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for
 * [Operations.ListOperations][google.longrunning.Operations.ListOperations].
 *
 * Generated from protobuf message <code>google.longrunning.ListOperationsRequest</code>
 */
class ListOperationsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the operation's parent resource.
     *
     * Generated from protobuf field <code>string name = 4 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * The standard list filter.
     *
     * Generated from protobuf field <code>string filter = 1 [json_name = "filter"];</code>
     */
    protected $filter = '';
    /**
     * The standard list page size.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize"];</code>
     */
    protected $page_size = 0;
    /**
     * The standard list page token.
     *
     * Generated from protobuf field <code>string page_token = 3 [json_name = "pageToken"];</code>
     */
    protected $page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the operation's parent resource.
     *     @type string $filter
     *           The standard list filter.
     *     @type int $page_size
     *           The standard list page size.
     *     @type string $page_token
     *           The standard list page token.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cbws\Longrunning\Operations::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the operation's parent resource.
     *
     * Generated from protobuf field <code>string name = 4 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the operation's parent resource.
     *
     * Generated from protobuf field <code>string name = 4 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The standard list filter.
     *
     * Generated from protobuf field <code>string filter = 1 [json_name = "filter"];</code>
     * @return string
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * The standard list filter.
     *
     * Generated from protobuf field <code>string filter = 1 [json_name = "filter"];</code>
     * @param string $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkString($var, True);
        $this->filter = $var;

        return $this;
    }

    /**
     * The standard list page size.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize"];</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * The standard list page size.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize"];</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * The standard list page token.
     *
     * Generated from protobuf field <code>string page_token = 3 [json_name = "pageToken"];</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * The standard list page token.
     *
     * Generated from protobuf field <code>string page_token = 3 [json_name = "pageToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

}

