<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/domains/v1alpha1/domain.proto

namespace Cbws\Domains\GRPC\V1alpha1\Metadata;

class Domain
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Cbws\IAM\Options\GRPC\V1alpha1\Metadata\Options::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\Client::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Duration::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af4040a22636277732f646f6d61696e732f7631616c706861312f646f6d" .
            "61696e2e70726f746f1215636277732e646f6d61696e732e7631616c7068" .
            "61311a1c676f6f676c652f6170692f616e6e6f746174696f6e732e70726f" .
            "746f1a17676f6f676c652f6170692f636c69656e742e70726f746f1a1f67" .
            "6f6f676c652f6170692f6669656c645f6265686176696f722e70726f746f" .
            "1a19676f6f676c652f6170692f7265736f757263652e70726f746f1a1b67" .
            "6f6f676c652f70726f746f6275662f656d7074792e70726f746f1a1e676f" .
            "6f676c652f70726f746f6275662f6475726174696f6e2e70726f746f1a1f" .
            "676f6f676c652f70726f746f6275662f74696d657374616d702e70726f74" .
            "6f22c6010a06446f6d61696e120c0a046e616d65180120012809120e0a06" .
            "706172656e7418022001280912110a09756e697175655f69641804200128" .
            "09120e0a06646f6d61696e180520012809120b0a03746c64180620012809" .
            "122a0a0665787069727918072001280b321a2e676f6f676c652e70726f74" .
            "6f6275662e54696d657374616d7012120a0a6175746f5f72656e65771808" .
            "200128083a2eea412b0a17646f6d61696e732e636277732e78797a2f446f" .
            "6d61696e1210646f6d61696e732f7b646f6d61696e7d4294010a1978797a" .
            "2e636277732e646f6d61696e732e7631616c7068613150015a3267697468" .
            "75622e636f6d2f636277732f676f2d636277732d677270632f636277732f" .
            "646f6d61696e732f7631616c70686131ca021a436277735c446f6d61696e" .
            "735c475250435c5631616c70686131e20223436277735c446f6d61696e73" .
            "5c475250435c5631616c706861315c4d65746164617461620670726f746f" .
            "33"
        ), true);

        static::$is_initialized = true;
    }
}

