<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/compute/v1alpha1/compute.proto

namespace Cbws\Grpc\Compute\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.compute.v1alpha1.CreateMachineRequest</code>
 */
class CreateMachineRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $parent = '';
    /**
     * Required. The name of the machine, without the projects prefix
     *
     * Generated from protobuf field <code>string machine_id = 2 [json_name = "machineId", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $machine_id = '';
    /**
     * The [Machine][cbws.compute.v1alpha1.Machine] resource to
     * create.
     *
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine machine = 3 [json_name = "machine", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $machine = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The resource name of the project associated with the service
     *           accounts, such as `projects/my-project-123`.
     *     @type string $machine_id
     *           Required. The name of the machine, without the projects prefix
     *     @type \Cbws\Grpc\Compute\V1alpha1\Machine $machine
     *           The [Machine][cbws.compute.v1alpha1.Machine] resource to
     *           create.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cbws\Compute\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Required. The name of the machine, without the projects prefix
     *
     * Generated from protobuf field <code>string machine_id = 2 [json_name = "machineId", (.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getMachineId()
    {
        return $this->machine_id;
    }

    /**
     * Required. The name of the machine, without the projects prefix
     *
     * Generated from protobuf field <code>string machine_id = 2 [json_name = "machineId", (.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setMachineId($var)
    {
        GPBUtil::checkString($var, True);
        $this->machine_id = $var;

        return $this;
    }

    /**
     * The [Machine][cbws.compute.v1alpha1.Machine] resource to
     * create.
     *
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine machine = 3 [json_name = "machine", (.google.api.field_behavior) = REQUIRED];</code>
     * @return \Cbws\Grpc\Compute\V1alpha1\Machine|null
     */
    public function getMachine()
    {
        return $this->machine;
    }

    public function hasMachine()
    {
        return isset($this->machine);
    }

    public function clearMachine()
    {
        unset($this->machine);
    }

    /**
     * The [Machine][cbws.compute.v1alpha1.Machine] resource to
     * create.
     *
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine machine = 3 [json_name = "machine", (.google.api.field_behavior) = REQUIRED];</code>
     * @param \Cbws\Grpc\Compute\V1alpha1\Machine $var
     * @return $this
     */
    public function setMachine($var)
    {
        GPBUtil::checkMessage($var, \Cbws\Grpc\Compute\V1alpha1\Machine::class);
        $this->machine = $var;

        return $this;
    }

}

