<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/compute/v1alpha1/compute.proto

namespace Cbws\Grpc\Compute\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.compute.v1alpha1.CreateMachineMetadata</code>
 */
class CreateMachineMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine.State state = 4 [json_name = "state", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine machine = 5 [json_name = "machine", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $machine = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $state
     *     @type \Cbws\Grpc\Compute\V1alpha1\Machine $machine
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\Grpc\Compute\V1alpha1\GPBMetadata\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine.State state = 4 [json_name = "state", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine.State state = 4 [json_name = "state", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Cbws\Grpc\Compute\V1alpha1\Machine\State::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine machine = 5 [json_name = "machine", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return \Cbws\Grpc\Compute\V1alpha1\Machine|null
     */
    public function getMachine()
    {
        return $this->machine;
    }

    public function hasMachine()
    {
        return isset($this->machine);
    }

    public function clearMachine()
    {
        unset($this->machine);
    }

    /**
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine machine = 5 [json_name = "machine", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param \Cbws\Grpc\Compute\V1alpha1\Machine $var
     * @return $this
     */
    public function setMachine($var)
    {
        GPBUtil::checkMessage($var, \Cbws\Grpc\Compute\V1alpha1\Machine::class);
        $this->machine = $var;

        return $this;
    }

}

