<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/compute/v1alpha1/image.proto

namespace Cbws\Grpc\Compute\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.compute.v1alpha1.Image</code>
 */
class Image extends \Google\Protobuf\Internal\Message
{
    /**
     * Resource name in format projects/project/images/image-name
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.google.api.field_behavior) = IMMUTABLE];</code>
     */
    protected $name = '';
    /**
     * Project name in format projects/project
     *
     * Generated from protobuf field <code>string parent = 2 [json_name = "parent", (.google.api.field_behavior) = IMMUTABLE];</code>
     */
    protected $parent = '';
    /**
     * Family of the image, for example projects/project/families/ubuntu-2204-lts-amd64
     *
     * Generated from protobuf field <code>string family = 3 [json_name = "family", (.google.api.field_behavior) = IMMUTABLE];</code>
     */
    protected $family = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Resource name in format projects/project/images/image-name
     *     @type string $parent
     *           Project name in format projects/project
     *     @type string $family
     *           Family of the image, for example projects/project/families/ubuntu-2204-lts-amd64
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cbws\Compute\Image::initOnce();
        parent::__construct($data);
    }

    /**
     * Resource name in format projects/project/images/image-name
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Resource name in format projects/project/images/image-name
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Project name in format projects/project
     *
     * Generated from protobuf field <code>string parent = 2 [json_name = "parent", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Project name in format projects/project
     *
     * Generated from protobuf field <code>string parent = 2 [json_name = "parent", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Family of the image, for example projects/project/families/ubuntu-2204-lts-amd64
     *
     * Generated from protobuf field <code>string family = 3 [json_name = "family", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @return string
     */
    public function getFamily()
    {
        return $this->family;
    }

    /**
     * Family of the image, for example projects/project/families/ubuntu-2204-lts-amd64
     *
     * Generated from protobuf field <code>string family = 3 [json_name = "family", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @param string $var
     * @return $this
     */
    public function setFamily($var)
    {
        GPBUtil::checkString($var, True);
        $this->family = $var;

        return $this;
    }

}

