<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/compute/v1alpha1/compute.proto

namespace Cbws\Grpc\Compute\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The machine list response.
 *
 * Generated from protobuf message <code>cbws.compute.v1alpha1.ListMachineTypesResponse</code>
 */
class ListMachineTypesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of matching machines.
     *
     * Generated from protobuf field <code>repeated .cbws.compute.v1alpha1.MachineType machine_types = 1 [json_name = "machineTypes"];</code>
     */
    private $machine_types;
    /**
     * To retrieve the next page of results, set
     * [ListMachineTypesRequest.page_token][cbws.compute.v1alpha1.ListMachineTypesRequest.page_token]
     * to this value.
     *
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Cbws\Grpc\Compute\V1alpha1\MachineType>|\Google\Protobuf\Internal\RepeatedField $machine_types
     *           The list of matching machines.
     *     @type string $next_page_token
     *           To retrieve the next page of results, set
     *           [ListMachineTypesRequest.page_token][cbws.compute.v1alpha1.ListMachineTypesRequest.page_token]
     *           to this value.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cbws\Compute\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of matching machines.
     *
     * Generated from protobuf field <code>repeated .cbws.compute.v1alpha1.MachineType machine_types = 1 [json_name = "machineTypes"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMachineTypes()
    {
        return $this->machine_types;
    }

    /**
     * The list of matching machines.
     *
     * Generated from protobuf field <code>repeated .cbws.compute.v1alpha1.MachineType machine_types = 1 [json_name = "machineTypes"];</code>
     * @param array<\Cbws\Grpc\Compute\V1alpha1\MachineType>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMachineTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cbws\Grpc\Compute\V1alpha1\MachineType::class);
        $this->machine_types = $arr;

        return $this;
    }

    /**
     * To retrieve the next page of results, set
     * [ListMachineTypesRequest.page_token][cbws.compute.v1alpha1.ListMachineTypesRequest.page_token]
     * to this value.
     *
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * To retrieve the next page of results, set
     * [ListMachineTypesRequest.page_token][cbws.compute.v1alpha1.ListMachineTypesRequest.page_token]
     * to this value.
     *
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

