<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/compute/v1alpha1/compute.proto

namespace Cbws\Grpc\Compute\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The machine types list request.
 *
 * Generated from protobuf message <code>cbws.compute.v1alpha1.ListMachineTypesRequest</code>
 */
class ListMachineTypesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $parent = '';
    /**
     * Optional limit on the number of machines to include in the
     * response. Further accounts can subsequently be obtained by including the
     * [ListMachineTypesResponse.next_page_token][cbws.compute.v1alpha1.ListMachineTypesResponse.next_page_token]
     * in a subsequent request.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize", (.google.api.field_behavior) = OPTIONAL];</code>
     */
    protected $page_size = 0;
    /**
     * Optional pagination token returned in an earlier
     * [ListMachineTypesResponse.next_page_token][cbws.compute.v1alpha1.ListMachineTypesResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [json_name = "pageToken", (.google.api.field_behavior) = OPTIONAL];</code>
     */
    protected $page_token = '';
    /**
     * Optional list of fields that should be included in the response, the service may include fields that haven't
     * been requested when they are available. This can be used to speed up requests as some fields can be more expensive
     * to lookup.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask read_mask = 4 [json_name = "readMask", (.google.api.field_behavior) = OPTIONAL];</code>
     */
    protected $read_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The resource name of the project associated with the service
     *           accounts, such as `projects/my-project-123`.
     *     @type int $page_size
     *           Optional limit on the number of machines to include in the
     *           response. Further accounts can subsequently be obtained by including the
     *           [ListMachineTypesResponse.next_page_token][cbws.compute.v1alpha1.ListMachineTypesResponse.next_page_token]
     *           in a subsequent request.
     *     @type string $page_token
     *           Optional pagination token returned in an earlier
     *           [ListMachineTypesResponse.next_page_token][cbws.compute.v1alpha1.ListMachineTypesResponse.next_page_token].
     *     @type \Google\Protobuf\FieldMask $read_mask
     *           Optional list of fields that should be included in the response, the service may include fields that haven't
     *           been requested when they are available. This can be used to speed up requests as some fields can be more expensive
     *           to lookup.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\Grpc\Compute\V1alpha1\GPBMetadata\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [json_name = "parent", (.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Optional limit on the number of machines to include in the
     * response. Further accounts can subsequently be obtained by including the
     * [ListMachineTypesResponse.next_page_token][cbws.compute.v1alpha1.ListMachineTypesResponse.next_page_token]
     * in a subsequent request.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Optional limit on the number of machines to include in the
     * response. Further accounts can subsequently be obtained by including the
     * [ListMachineTypesResponse.next_page_token][cbws.compute.v1alpha1.ListMachineTypesResponse.next_page_token]
     * in a subsequent request.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Optional pagination token returned in an earlier
     * [ListMachineTypesResponse.next_page_token][cbws.compute.v1alpha1.ListMachineTypesResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [json_name = "pageToken", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * Optional pagination token returned in an earlier
     * [ListMachineTypesResponse.next_page_token][cbws.compute.v1alpha1.ListMachineTypesResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [json_name = "pageToken", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

    /**
     * Optional list of fields that should be included in the response, the service may include fields that haven't
     * been requested when they are available. This can be used to speed up requests as some fields can be more expensive
     * to lookup.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask read_mask = 4 [json_name = "readMask", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getReadMask()
    {
        return $this->read_mask;
    }

    public function hasReadMask()
    {
        return isset($this->read_mask);
    }

    public function clearReadMask()
    {
        unset($this->read_mask);
    }

    /**
     * Optional list of fields that should be included in the response, the service may include fields that haven't
     * been requested when they are available. This can be used to speed up requests as some fields can be more expensive
     * to lookup.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask read_mask = 4 [json_name = "readMask", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setReadMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->read_mask = $var;

        return $this;
    }

}

