<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/compute/v1alpha1/machine.proto

namespace Cbws\Grpc\Compute\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.compute.v1alpha1.Machine</code>
 */
class Machine extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.google.api.field_behavior) = IMMUTABLE];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string parent = 2 [json_name = "parent", (.google.api.field_behavior) = IMMUTABLE];</code>
     */
    protected $parent = '';
    /**
     * Generated from protobuf field <code>string type = 3 [json_name = "type", (.google.api.field_behavior) = IMMUTABLE];</code>
     */
    protected $type = '';
    /**
     * Which image to use, can either be projects/project-name/families/ubuntu-2204-lts
     * or projects/project-name/images/ubuntu-2204-lts-image-tag
     *
     * Generated from protobuf field <code>string image = 10 [json_name = "image", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $image = '';
    /**
     * Generated from protobuf field <code>string hostname = 4 [json_name = "hostname", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $hostname = '';
    /**
     * The IPv6 address of the instance
     *
     * Generated from protobuf field <code>string address = 7 [json_name = "address", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>repeated string ssh_keys = 9 [json_name = "sshKeys", (.google.api.field_behavior) = IMMUTABLE];</code>
     */
    private $ssh_keys;
    /**
     * Generated from protobuf field <code>string userdata = 16 [json_name = "userdata", (.google.api.field_behavior) = IMMUTABLE];</code>
     */
    protected $userdata = '';
    /**
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine.State state = 8 [json_name = "state", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $state = 0;
    /**
     * A list of labels useful for filtering, affinities and load balancing.
     *
     * Generated from protobuf field <code>map<string, string> labels = 11 [json_name = "labels", (.google.api.field_behavior) = OPTIONAL];</code>
     */
    private $labels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $parent
     *     @type string $type
     *     @type string $image
     *           Which image to use, can either be projects/project-name/families/ubuntu-2204-lts
     *           or projects/project-name/images/ubuntu-2204-lts-image-tag
     *     @type string $hostname
     *     @type string $address
     *           The IPv6 address of the instance
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $ssh_keys
     *     @type string $userdata
     *     @type int $state
     *     @type array|\Google\Protobuf\Internal\MapField $labels
     *           A list of labels useful for filtering, affinities and load balancing.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cbws\Compute\Machine::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parent = 2 [json_name = "parent", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Generated from protobuf field <code>string parent = 2 [json_name = "parent", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 3 [json_name = "type", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 3 [json_name = "type", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Which image to use, can either be projects/project-name/families/ubuntu-2204-lts
     * or projects/project-name/images/ubuntu-2204-lts-image-tag
     *
     * Generated from protobuf field <code>string image = 10 [json_name = "image", (.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Which image to use, can either be projects/project-name/families/ubuntu-2204-lts
     * or projects/project-name/images/ubuntu-2204-lts-image-tag
     *
     * Generated from protobuf field <code>string image = 10 [json_name = "image", (.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hostname = 4 [json_name = "hostname", (.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * Generated from protobuf field <code>string hostname = 4 [json_name = "hostname", (.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setHostname($var)
    {
        GPBUtil::checkString($var, True);
        $this->hostname = $var;

        return $this;
    }

    /**
     * The IPv6 address of the instance
     *
     * Generated from protobuf field <code>string address = 7 [json_name = "address", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * The IPv6 address of the instance
     *
     * Generated from protobuf field <code>string address = 7 [json_name = "address", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string ssh_keys = 9 [json_name = "sshKeys", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSshKeys()
    {
        return $this->ssh_keys;
    }

    /**
     * Generated from protobuf field <code>repeated string ssh_keys = 9 [json_name = "sshKeys", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSshKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ssh_keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userdata = 16 [json_name = "userdata", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @return string
     */
    public function getUserdata()
    {
        return $this->userdata;
    }

    /**
     * Generated from protobuf field <code>string userdata = 16 [json_name = "userdata", (.google.api.field_behavior) = IMMUTABLE];</code>
     * @param string $var
     * @return $this
     */
    public function setUserdata($var)
    {
        GPBUtil::checkString($var, True);
        $this->userdata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine.State state = 8 [json_name = "state", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine.State state = 8 [json_name = "state", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Cbws\Grpc\Compute\V1alpha1\Machine\State::class);
        $this->state = $var;

        return $this;
    }

    /**
     * A list of labels useful for filtering, affinities and load balancing.
     *
     * Generated from protobuf field <code>map<string, string> labels = 11 [json_name = "labels", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getLabels()
    {
        return $this->labels;
    }

    /**
     * A list of labels useful for filtering, affinities and load balancing.
     *
     * Generated from protobuf field <code>map<string, string> labels = 11 [json_name = "labels", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setLabels($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->labels = $arr;

        return $this;
    }

}

