<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/compute/v1alpha1/machine_type.proto

namespace Cbws\Grpc\Compute\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.compute.v1alpha1.MachineType</code>
 */
class MachineType extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the resource
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $name = '';
    /**
     * Either nl-ein-1 or nl-ein-2.
     *
     * Generated from protobuf field <code>string zone = 3 [json_name = "zone", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $zone = '';
    /**
     * Amount of (virtual) CPU cores available to the machine.
     *
     * Generated from protobuf field <code>int32 cpu = 4 [json_name = "cpu", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $cpu = 0;
    /**
     * Amount of RAM available to the machine in MB.
     *
     * Generated from protobuf field <code>int32 memory_mb = 5 [json_name = "memoryMb", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $memory_mb = 0;
    /**
     * Amount of ephemeral disk space available to the machine in GB, this is a non volume backed disk.
     *
     * Generated from protobuf field <code>int32 ephemeral_disk_gb = 6 [json_name = "ephemeralDiskGb", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    protected $ephemeral_disk_gb = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name of the resource
     *     @type string $zone
     *           Either nl-ein-1 or nl-ein-2.
     *     @type int $cpu
     *           Amount of (virtual) CPU cores available to the machine.
     *     @type int $memory_mb
     *           Amount of RAM available to the machine in MB.
     *     @type int $ephemeral_disk_gb
     *           Amount of ephemeral disk space available to the machine in GB, this is a non volume backed disk.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\Grpc\Compute\V1alpha1\GPBMetadata\MachineType::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the resource
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the resource
     *
     * Generated from protobuf field <code>string name = 1 [json_name = "name", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Either nl-ein-1 or nl-ein-2.
     *
     * Generated from protobuf field <code>string zone = 3 [json_name = "zone", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return string
     */
    public function getZone()
    {
        return $this->zone;
    }

    /**
     * Either nl-ein-1 or nl-ein-2.
     *
     * Generated from protobuf field <code>string zone = 3 [json_name = "zone", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param string $var
     * @return $this
     */
    public function setZone($var)
    {
        GPBUtil::checkString($var, True);
        $this->zone = $var;

        return $this;
    }

    /**
     * Amount of (virtual) CPU cores available to the machine.
     *
     * Generated from protobuf field <code>int32 cpu = 4 [json_name = "cpu", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return int
     */
    public function getCpu()
    {
        return $this->cpu;
    }

    /**
     * Amount of (virtual) CPU cores available to the machine.
     *
     * Generated from protobuf field <code>int32 cpu = 4 [json_name = "cpu", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param int $var
     * @return $this
     */
    public function setCpu($var)
    {
        GPBUtil::checkInt32($var);
        $this->cpu = $var;

        return $this;
    }

    /**
     * Amount of RAM available to the machine in MB.
     *
     * Generated from protobuf field <code>int32 memory_mb = 5 [json_name = "memoryMb", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return int
     */
    public function getMemoryMb()
    {
        return $this->memory_mb;
    }

    /**
     * Amount of RAM available to the machine in MB.
     *
     * Generated from protobuf field <code>int32 memory_mb = 5 [json_name = "memoryMb", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param int $var
     * @return $this
     */
    public function setMemoryMb($var)
    {
        GPBUtil::checkInt32($var);
        $this->memory_mb = $var;

        return $this;
    }

    /**
     * Amount of ephemeral disk space available to the machine in GB, this is a non volume backed disk.
     *
     * Generated from protobuf field <code>int32 ephemeral_disk_gb = 6 [json_name = "ephemeralDiskGb", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return int
     */
    public function getEphemeralDiskGb()
    {
        return $this->ephemeral_disk_gb;
    }

    /**
     * Amount of ephemeral disk space available to the machine in GB, this is a non volume backed disk.
     *
     * Generated from protobuf field <code>int32 ephemeral_disk_gb = 6 [json_name = "ephemeralDiskGb", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param int $var
     * @return $this
     */
    public function setEphemeralDiskGb($var)
    {
        GPBUtil::checkInt32($var);
        $this->ephemeral_disk_gb = $var;

        return $this;
    }

}

