<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/compute/v1alpha1/compute.proto

namespace Cbws\Grpc\Compute\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.compute.v1alpha1.UpdateMachineRequest</code>
 */
class UpdateMachineRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The [Machine][cbws.compute.v1alpha1.Machine] resource to
     * update.
     *
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine machine = 1 [json_name = "machine", (.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $machine = null;
    /**
     * The list of fields to be updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2 [json_name = "updateMask", (.google.api.field_behavior) = OPTIONAL];</code>
     */
    protected $update_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\Grpc\Compute\V1alpha1\Machine $machine
     *           The [Machine][cbws.compute.v1alpha1.Machine] resource to
     *           update.
     *     @type \Google\Protobuf\FieldMask $update_mask
     *           The list of fields to be updated.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\Grpc\Compute\V1alpha1\GPBMetadata\Compute::initOnce();
        parent::__construct($data);
    }

    /**
     * The [Machine][cbws.compute.v1alpha1.Machine] resource to
     * update.
     *
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine machine = 1 [json_name = "machine", (.google.api.field_behavior) = REQUIRED];</code>
     * @return \Cbws\Grpc\Compute\V1alpha1\Machine|null
     */
    public function getMachine()
    {
        return $this->machine;
    }

    public function hasMachine()
    {
        return isset($this->machine);
    }

    public function clearMachine()
    {
        unset($this->machine);
    }

    /**
     * The [Machine][cbws.compute.v1alpha1.Machine] resource to
     * update.
     *
     * Generated from protobuf field <code>.cbws.compute.v1alpha1.Machine machine = 1 [json_name = "machine", (.google.api.field_behavior) = REQUIRED];</code>
     * @param \Cbws\Grpc\Compute\V1alpha1\Machine $var
     * @return $this
     */
    public function setMachine($var)
    {
        GPBUtil::checkMessage($var, \Cbws\Grpc\Compute\V1alpha1\Machine::class);
        $this->machine = $var;

        return $this;
    }

    /**
     * The list of fields to be updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2 [json_name = "updateMask", (.google.api.field_behavior) = OPTIONAL];</code>
     * @return \Google\Protobuf\FieldMask|null
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    public function hasUpdateMask()
    {
        return isset($this->update_mask);
    }

    public function clearUpdateMask()
    {
        unset($this->update_mask);
    }

    /**
     * The list of fields to be updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2 [json_name = "updateMask", (.google.api.field_behavior) = OPTIONAL];</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

}

