<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/projects/v1alpha1/project.proto

namespace Cbws\Projects\GRPC\V1alpha1\Metadata;

class Project
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Resource::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acf020a24636277732f70726f6a656374732f7631616c706861312f7072" .
            "6f6a6563742e70726f746f1216636277732e70726f6a656374732e763161" .
            "6c70686131228a010a0750726f6a656374120c0a046e616d651801200128" .
            "0912140a0c646973706c61795f6e616d6518022001280912140a0c6f7267" .
            "616e697a6174696f6e18032001280912110a09756e697175655f69641804" .
            "200128093a32ea412f0a1970726f6a656374732e636277732e78797a2f50" .
            "726f6a656374121270726f6a656374732f7b70726f6a6563747d427a5a33" .
            "6769746875622e636f6d2f636277732f676f2d636277732d677270632f63" .
            "6277732f70726f6a656374732f7631616c70686131ca021b436277735c50" .
            "726f6a656374735c475250435c5631616c70686131e20224436277735c50" .
            "726f6a656374735c475250435c5631616c706861315c4d65746164617461" .
            "620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

