<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/service_management/service_usage/v1alpha1/service_management.proto

namespace Cbws\ServiceUsage\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request message for DisableService method.
 *
 * Generated from protobuf message <code>cbws.service_management.service_usage.v1alpha1.DisableServiceRequest</code>
 */
class DisableServiceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Relative resource of service in project in format: projects/test-project/services/iam.cbws.xyz
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Relative resource of service in project in format: projects/test-project/services/iam.cbws.xyz
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\ServiceUsage\GRPC\V1alpha1\Metadata\ServiceManagement::initOnce();
        parent::__construct($data);
    }

    /**
     * Relative resource of service in project in format: projects/test-project/services/iam.cbws.xyz
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Relative resource of service in project in format: projects/test-project/services/iam.cbws.xyz
     *
     * Generated from protobuf field <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

