<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/service_management/service_usage/v1alpha1/service_management.proto

namespace Cbws\ServiceUsage\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.service_management.service_usage.v1alpha1.ListServicesResponse</code>
 */
class ListServicesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of matching services.
     *
     * Generated from protobuf field <code>repeated .cbws.service_management.service_usage.v1alpha1.Service services = 1;</code>
     */
    private $services;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\ServiceUsage\GRPC\V1alpha1\Service[]|\Google\Protobuf\Internal\RepeatedField $services
     *           The list of matching services.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\ServiceUsage\GRPC\V1alpha1\Metadata\ServiceManagement::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of matching services.
     *
     * Generated from protobuf field <code>repeated .cbws.service_management.service_usage.v1alpha1.Service services = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServices()
    {
        return $this->services;
    }

    /**
     * The list of matching services.
     *
     * Generated from protobuf field <code>repeated .cbws.service_management.service_usage.v1alpha1.Service services = 1;</code>
     * @param \Cbws\ServiceUsage\GRPC\V1alpha1\Service[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cbws\ServiceUsage\GRPC\V1alpha1\Service::class);
        $this->services = $arr;

        return $this;
    }

}

