<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/service_management/service_usage/v1alpha1/service.proto

namespace Cbws\ServiceUsage\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.service_management.service_usage.v1alpha1.Service</code>
 */
class Service extends \Google\Protobuf\Internal\Message
{
    /**
     * Service relative resource name, in the format of projects/test-project/services/k8s.cbws.xyz
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Relative resource name of the parent resource, for example projects/test-project
     *
     * Generated from protobuf field <code>string parent = 2;</code>
     */
    protected $parent = '';
    /**
     * Overall information about the service, including service name (k8s.cbws.xyz) and title
     *
     * Generated from protobuf field <code>.cbws.service_management.service_usage.v1alpha1.ServiceConfig config = 3;</code>
     */
    protected $config = null;
    /**
     * Whether the service is enabled on this project or not
     *
     * Generated from protobuf field <code>.cbws.service_management.service_usage.v1alpha1.ServiceState state = 4;</code>
     */
    protected $state = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Service relative resource name, in the format of projects/test-project/services/k8s.cbws.xyz
     *     @type string $parent
     *           Relative resource name of the parent resource, for example projects/test-project
     *     @type \Cbws\ServiceUsage\GRPC\V1alpha1\ServiceConfig $config
     *           Overall information about the service, including service name (k8s.cbws.xyz) and title
     *     @type int $state
     *           Whether the service is enabled on this project or not
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\ServiceUsage\GRPC\V1alpha1\Metadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Service relative resource name, in the format of projects/test-project/services/k8s.cbws.xyz
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Service relative resource name, in the format of projects/test-project/services/k8s.cbws.xyz
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Relative resource name of the parent resource, for example projects/test-project
     *
     * Generated from protobuf field <code>string parent = 2;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Relative resource name of the parent resource, for example projects/test-project
     *
     * Generated from protobuf field <code>string parent = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Overall information about the service, including service name (k8s.cbws.xyz) and title
     *
     * Generated from protobuf field <code>.cbws.service_management.service_usage.v1alpha1.ServiceConfig config = 3;</code>
     * @return \Cbws\ServiceUsage\GRPC\V1alpha1\ServiceConfig
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Overall information about the service, including service name (k8s.cbws.xyz) and title
     *
     * Generated from protobuf field <code>.cbws.service_management.service_usage.v1alpha1.ServiceConfig config = 3;</code>
     * @param \Cbws\ServiceUsage\GRPC\V1alpha1\ServiceConfig $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \Cbws\ServiceUsage\GRPC\V1alpha1\ServiceConfig::class);
        $this->config = $var;

        return $this;
    }

    /**
     * Whether the service is enabled on this project or not
     *
     * Generated from protobuf field <code>.cbws.service_management.service_usage.v1alpha1.ServiceState state = 4;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Whether the service is enabled on this project or not
     *
     * Generated from protobuf field <code>.cbws.service_management.service_usage.v1alpha1.ServiceState state = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Cbws\ServiceUsage\GRPC\V1alpha1\ServiceState::class);
        $this->state = $var;

        return $this;
    }

}

