<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/service_management/service_usage/v1alpha1/service.proto

namespace Cbws\ServiceUsage\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.service_management.service_usage.v1alpha1.ServiceConfig</code>
 */
class ServiceConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the service, for example k8s.cbws.xyz
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * The title of the product of the service, for example Kubernetes
     *
     * Generated from protobuf field <code>string title = 2;</code>
     */
    protected $title = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the service, for example k8s.cbws.xyz
     *     @type string $title
     *           The title of the product of the service, for example Kubernetes
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\ServiceUsage\GRPC\V1alpha1\Metadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the service, for example k8s.cbws.xyz
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the service, for example k8s.cbws.xyz
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The title of the product of the service, for example Kubernetes
     *
     * Generated from protobuf field <code>string title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * The title of the product of the service, for example Kubernetes
     *
     * Generated from protobuf field <code>string title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

}

