<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/service_management/service_usage/v1alpha1/service.proto

namespace Cbws\ServiceUsage\GRPC\V1alpha1;

use UnexpectedValueException;

/**
 * Protobuf type <code>cbws.service_management.service_usage.v1alpha1.ServiceState</code>
 */
class ServiceState
{
    /**
     * Generated from protobuf enum <code>SERVICE_STATE_UNSPECIFIED = 0;</code>
     */
    const SERVICE_STATE_UNSPECIFIED = 0;
    /**
     * Service is currently not enabled in the consumer project
     *
     * Generated from protobuf enum <code>SERVICE_STATE_DISABLED = 1;</code>
     */
    const SERVICE_STATE_DISABLED = 1;
    /**
     * Service is enabled in the consumer project and can be used
     *
     * Generated from protobuf enum <code>SERVICE_STATE_ENABLED = 2;</code>
     */
    const SERVICE_STATE_ENABLED = 2;

    private static $valueToName = [
        self::SERVICE_STATE_UNSPECIFIED => 'SERVICE_STATE_UNSPECIFIED',
        self::SERVICE_STATE_DISABLED => 'SERVICE_STATE_DISABLED',
        self::SERVICE_STATE_ENABLED => 'SERVICE_STATE_ENABLED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

