<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/logging/v1alpha1/logging.proto

namespace Cbws\Logging\Grpc\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Result returned from ListLogs.
 *
 * Generated from protobuf message <code>cbws.logging.v1alpha1.ListLogsResponse</code>
 */
class ListLogsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of log names. For example,
     * `"projects/my-project/logs/syslog"` or
     * `"organizations/123/logs/cloudresourcemanager.googleapis.com%2Factivity"`.
     *
     * Generated from protobuf field <code>repeated .cbws.logging.v1alpha1.Log logs = 1;</code>
     */
    private $logs;
    /**
     * If there might be more results than those appearing in this response, then
     * `nextPageToken` is included.  To get the next set of results, call this
     * method again using the value of `nextPageToken` as `pageToken`.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\Logging\Grpc\V1alpha1\Log[]|\Google\Protobuf\Internal\RepeatedField $logs
     *           A list of log names. For example,
     *           `"projects/my-project/logs/syslog"` or
     *           `"organizations/123/logs/cloudresourcemanager.googleapis.com%2Factivity"`.
     *     @type string $next_page_token
     *           If there might be more results than those appearing in this response, then
     *           `nextPageToken` is included.  To get the next set of results, call this
     *           method again using the value of `nextPageToken` as `pageToken`.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\Logging\Grpc\V1alpha1\Metadata\Logging::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of log names. For example,
     * `"projects/my-project/logs/syslog"` or
     * `"organizations/123/logs/cloudresourcemanager.googleapis.com%2Factivity"`.
     *
     * Generated from protobuf field <code>repeated .cbws.logging.v1alpha1.Log logs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLogs()
    {
        return $this->logs;
    }

    /**
     * A list of log names. For example,
     * `"projects/my-project/logs/syslog"` or
     * `"organizations/123/logs/cloudresourcemanager.googleapis.com%2Factivity"`.
     *
     * Generated from protobuf field <code>repeated .cbws.logging.v1alpha1.Log logs = 1;</code>
     * @param \Cbws\Logging\Grpc\V1alpha1\Log[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLogs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cbws\Logging\Grpc\V1alpha1\Log::class);
        $this->logs = $arr;

        return $this;
    }

    /**
     * If there might be more results than those appearing in this response, then
     * `nextPageToken` is included.  To get the next set of results, call this
     * method again using the value of `nextPageToken` as `pageToken`.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * If there might be more results than those appearing in this response, then
     * `nextPageToken` is included.  To get the next set of results, call this
     * method again using the value of `nextPageToken` as `pageToken`.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

