<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/virtual_machines/v1alpha1/vm.proto

namespace Cbws\VirtualMachines\Grpc\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.virtual_machines.v1alpha1.CreateInstanceRequest</code>
 */
class CreateInstanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $parent = '';
    /**
     * Required. The name of the instance, without the projects prefix
     *
     * Generated from protobuf field <code>string instance_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $instance_id = '';
    /**
     * The [Instance][cbws.virtual_machines.v1alpha1.Instance] resource to
     * create.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.v1alpha1.Instance instance = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $instance = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The resource name of the project associated with the service
     *           accounts, such as `projects/my-project-123`.
     *     @type string $instance_id
     *           Required. The name of the instance, without the projects prefix
     *     @type \Cbws\VirtualMachines\Grpc\V1alpha1\Instance $instance
     *           The [Instance][cbws.virtual_machines.v1alpha1.Instance] resource to
     *           create.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\VirtualMachines\Grpc\V1alpha1\Metadata\Vm::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Required. The name of the instance, without the projects prefix
     *
     * Generated from protobuf field <code>string instance_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getInstanceId()
    {
        return $this->instance_id;
    }

    /**
     * Required. The name of the instance, without the projects prefix
     *
     * Generated from protobuf field <code>string instance_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setInstanceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->instance_id = $var;

        return $this;
    }

    /**
     * The [Instance][cbws.virtual_machines.v1alpha1.Instance] resource to
     * create.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.v1alpha1.Instance instance = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Cbws\VirtualMachines\Grpc\V1alpha1\Instance
     */
    public function getInstance()
    {
        return $this->instance;
    }

    /**
     * The [Instance][cbws.virtual_machines.v1alpha1.Instance] resource to
     * create.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.v1alpha1.Instance instance = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Cbws\VirtualMachines\Grpc\V1alpha1\Instance $var
     * @return $this
     */
    public function setInstance($var)
    {
        GPBUtil::checkMessage($var, \Cbws\VirtualMachines\Grpc\V1alpha1\Instance::class);
        $this->instance = $var;

        return $this;
    }

}

