<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/virtual_machines/v1alpha1/instance.proto

namespace Cbws\VirtualMachines\Grpc\V1alpha1;

if (false) {
    /**
     * This class is deprecated. Use Cbws\VirtualMachines\Grpc\V1alpha1\Instance\State instead.
     * @deprecated
     */
    class Instance_State {}
}
class_exists(Instance\State::class);
@trigger_error('Cbws\VirtualMachines\Grpc\V1alpha1\Instance_State is deprecated and will be removed in the next major release. Use Cbws\VirtualMachines\Grpc\V1alpha1\Instance\State instead', E_USER_DEPRECATED);

