<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/virtual_machines/v1alpha1/instance.proto

namespace Cbws\VirtualMachines\Grpc\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.virtual_machines.v1alpha1.Instance</code>
 */
class Instance extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string parent = 2;</code>
     */
    protected $parent = '';
    /**
     * Generated from protobuf field <code>string hostname = 3;</code>
     */
    protected $hostname = '';
    /**
     * Generated from protobuf field <code>int64 cpu = 4;</code>
     */
    protected $cpu = 0;
    /**
     * Generated from protobuf field <code>int64 memory = 5;</code>
     */
    protected $memory = 0;
    /**
     * Generated from protobuf field <code>int64 root_disk = 6;</code>
     */
    protected $root_disk = 0;
    /**
     * The IPv6 address of the instance
     *
     * Generated from protobuf field <code>string address = 7;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>repeated string ssh_keys = 9;</code>
     */
    private $ssh_keys;
    /**
     * Generated from protobuf field <code>.cbws.virtual_machines.v1alpha1.Instance.State state = 8;</code>
     */
    protected $state = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $parent
     *     @type string $hostname
     *     @type int|string $cpu
     *     @type int|string $memory
     *     @type int|string $root_disk
     *     @type string $address
     *           The IPv6 address of the instance
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $ssh_keys
     *     @type int $state
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\VirtualMachines\Grpc\V1alpha1\Metadata\Instance::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parent = 2;</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Generated from protobuf field <code>string parent = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hostname = 3;</code>
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * Generated from protobuf field <code>string hostname = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHostname($var)
    {
        GPBUtil::checkString($var, True);
        $this->hostname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 cpu = 4;</code>
     * @return int|string
     */
    public function getCpu()
    {
        return $this->cpu;
    }

    /**
     * Generated from protobuf field <code>int64 cpu = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCpu($var)
    {
        GPBUtil::checkInt64($var);
        $this->cpu = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 memory = 5;</code>
     * @return int|string
     */
    public function getMemory()
    {
        return $this->memory;
    }

    /**
     * Generated from protobuf field <code>int64 memory = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemory($var)
    {
        GPBUtil::checkInt64($var);
        $this->memory = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 root_disk = 6;</code>
     * @return int|string
     */
    public function getRootDisk()
    {
        return $this->root_disk;
    }

    /**
     * Generated from protobuf field <code>int64 root_disk = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRootDisk($var)
    {
        GPBUtil::checkInt64($var);
        $this->root_disk = $var;

        return $this;
    }

    /**
     * The IPv6 address of the instance
     *
     * Generated from protobuf field <code>string address = 7;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * The IPv6 address of the instance
     *
     * Generated from protobuf field <code>string address = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string ssh_keys = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSshKeys()
    {
        return $this->ssh_keys;
    }

    /**
     * Generated from protobuf field <code>repeated string ssh_keys = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSshKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ssh_keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.cbws.virtual_machines.v1alpha1.Instance.State state = 8;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.cbws.virtual_machines.v1alpha1.Instance.State state = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Cbws\VirtualMachines\Grpc\V1alpha1\Instance_State::class);
        $this->state = $var;

        return $this;
    }

}

