<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/virtual_machines/v1alpha1/vm.proto

namespace Cbws\VirtualMachines\Grpc\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The instance list request.
 *
 * Generated from protobuf message <code>cbws.virtual_machines.v1alpha1.ListInstancesRequest</code>
 */
class ListInstancesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $parent = '';
    /**
     * Optional limit on the number of instances to include in the
     * response. Further accounts can subsequently be obtained by including the
     * [ListInstancesResponse.next_page_token][cbws.virtual_machines.v1alpha1.ListInstancesResponse.next_page_token]
     * in a subsequent request.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
     */
    protected $page_size = 0;
    /**
     * Optional pagination token returned in an earlier
     * [ListInstancesResponse.next_page_token][cbws.virtual_machines.v1alpha1.ListInstancesResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     */
    protected $page_token = '';
    /**
     * Optional list of fields that should be included in the response, the service may include fields that haven't
     * been requested when they are available. This can be used to speed up requests as some fields can be more expensive
     * to lookup.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask read_mask = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
     */
    protected $read_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The resource name of the project associated with the service
     *           accounts, such as `projects/my-project-123`.
     *     @type int $page_size
     *           Optional limit on the number of instances to include in the
     *           response. Further accounts can subsequently be obtained by including the
     *           [ListInstancesResponse.next_page_token][cbws.virtual_machines.v1alpha1.ListInstancesResponse.next_page_token]
     *           in a subsequent request.
     *     @type string $page_token
     *           Optional pagination token returned in an earlier
     *           [ListInstancesResponse.next_page_token][cbws.virtual_machines.v1alpha1.ListInstancesResponse.next_page_token].
     *     @type \Google\Protobuf\FieldMask $read_mask
     *           Optional list of fields that should be included in the response, the service may include fields that haven't
     *           been requested when they are available. This can be used to speed up requests as some fields can be more expensive
     *           to lookup.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\VirtualMachines\Grpc\V1alpha1\Metadata\Vm::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Optional limit on the number of instances to include in the
     * response. Further accounts can subsequently be obtained by including the
     * [ListInstancesResponse.next_page_token][cbws.virtual_machines.v1alpha1.ListInstancesResponse.next_page_token]
     * in a subsequent request.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Optional limit on the number of instances to include in the
     * response. Further accounts can subsequently be obtained by including the
     * [ListInstancesResponse.next_page_token][cbws.virtual_machines.v1alpha1.ListInstancesResponse.next_page_token]
     * in a subsequent request.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Optional pagination token returned in an earlier
     * [ListInstancesResponse.next_page_token][cbws.virtual_machines.v1alpha1.ListInstancesResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * Optional pagination token returned in an earlier
     * [ListInstancesResponse.next_page_token][cbws.virtual_machines.v1alpha1.ListInstancesResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

    /**
     * Optional list of fields that should be included in the response, the service may include fields that haven't
     * been requested when they are available. This can be used to speed up requests as some fields can be more expensive
     * to lookup.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask read_mask = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @return \Google\Protobuf\FieldMask
     */
    public function getReadMask()
    {
        return $this->read_mask;
    }

    /**
     * Optional list of fields that should be included in the response, the service may include fields that haven't
     * been requested when they are available. This can be used to speed up requests as some fields can be more expensive
     * to lookup.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask read_mask = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setReadMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->read_mask = $var;

        return $this;
    }

}

