<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/virtual_machines/v1alpha1/vm.proto

namespace Cbws\VirtualMachines\Grpc\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.virtual_machines.v1alpha1.UpdateInstanceRequest</code>
 */
class UpdateInstanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The [Instance][cbws.virtual_machines.v1alpha1.Instance] resource to
     * update.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.v1alpha1.Instance instance = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $instance = null;
    /**
     * The list of fields to be updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    protected $update_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\VirtualMachines\Grpc\V1alpha1\Instance $instance
     *           The [Instance][cbws.virtual_machines.v1alpha1.Instance] resource to
     *           update.
     *     @type \Google\Protobuf\FieldMask $update_mask
     *           The list of fields to be updated.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\VirtualMachines\Grpc\V1alpha1\Metadata\Vm::initOnce();
        parent::__construct($data);
    }

    /**
     * The [Instance][cbws.virtual_machines.v1alpha1.Instance] resource to
     * update.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.v1alpha1.Instance instance = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Cbws\VirtualMachines\Grpc\V1alpha1\Instance
     */
    public function getInstance()
    {
        return $this->instance;
    }

    /**
     * The [Instance][cbws.virtual_machines.v1alpha1.Instance] resource to
     * update.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.v1alpha1.Instance instance = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Cbws\VirtualMachines\Grpc\V1alpha1\Instance $var
     * @return $this
     */
    public function setInstance($var)
    {
        GPBUtil::checkMessage($var, \Cbws\VirtualMachines\Grpc\V1alpha1\Instance::class);
        $this->instance = $var;

        return $this;
    }

    /**
     * The list of fields to be updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @return \Google\Protobuf\FieldMask
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    /**
     * The list of fields to be updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

}

