<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/iam/options/v1alpha1/options.proto

namespace Cbws\IAM\Options\GRPC\V1alpha1;

use UnexpectedValueException;

/**
 * Protobuf type <code>cbws.iam.options.v1alpha1.ResourceField</code>
 */
class ResourceField
{
    /**
     * Generated from protobuf enum <code>RESOURCE_FIELD_UNSPECIFIED = 0;</code>
     */
    const RESOURCE_FIELD_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>RESOURCE_FIELD_ORGANIZATION_NAME = 1;</code>
     */
    const RESOURCE_FIELD_ORGANIZATION_NAME = 1;
    /**
     * Generated from protobuf enum <code>RESOURCE_FIELD_PROJECT_NAME = 2;</code>
     */
    const RESOURCE_FIELD_PROJECT_NAME = 2;
    /**
     * Generated from protobuf enum <code>RESOURCE_FIELD_NAME = 3;</code>
     */
    const RESOURCE_FIELD_NAME = 3;
    /**
     * Generated from protobuf enum <code>RESOURCE_FIELD_ORGANIZATION_ID = 11;</code>
     */
    const RESOURCE_FIELD_ORGANIZATION_ID = 11;
    /**
     * Generated from protobuf enum <code>RESOURCE_FIELD_PROJECT_ID = 21;</code>
     */
    const RESOURCE_FIELD_PROJECT_ID = 21;
    /**
     * Generated from protobuf enum <code>RESOURCE_FIELD_ID = 31;</code>
     */
    const RESOURCE_FIELD_ID = 31;

    private static $valueToName = [
        self::RESOURCE_FIELD_UNSPECIFIED => 'RESOURCE_FIELD_UNSPECIFIED',
        self::RESOURCE_FIELD_ORGANIZATION_NAME => 'RESOURCE_FIELD_ORGANIZATION_NAME',
        self::RESOURCE_FIELD_PROJECT_NAME => 'RESOURCE_FIELD_PROJECT_NAME',
        self::RESOURCE_FIELD_NAME => 'RESOURCE_FIELD_NAME',
        self::RESOURCE_FIELD_ORGANIZATION_ID => 'RESOURCE_FIELD_ORGANIZATION_ID',
        self::RESOURCE_FIELD_PROJECT_ID => 'RESOURCE_FIELD_PROJECT_ID',
        self::RESOURCE_FIELD_ID => 'RESOURCE_FIELD_ID',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

