<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/iam/options/v1alpha1/options.proto

namespace GPBMetadata\Cbws\Iam\Options;

class Options
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xEC\x04\x0A'cbws/iam/options/v1alpha1/options.proto\x12\x19cbws.iam.options.v1alpha1\x1A google/protobuf/descriptor.proto\"#\x0A\x07Service\x12\x18\x0A\x07service\x18\x01 \x01(\x09R\x07service*\xE9\x01\x0A\x0DResourceField\x12\x1E\x0A\x1ARESOURCE_FIELD_UNSPECIFIED\x10\x00\x12\$\x0A RESOURCE_FIELD_ORGANIZATION_NAME\x10\x01\x12\x1F\x0A\x1BRESOURCE_FIELD_PROJECT_NAME\x10\x02\x12\x17\x0A\x13RESOURCE_FIELD_NAME\x10\x03\x12\"\x0A\x1ERESOURCE_FIELD_ORGANIZATION_ID\x10\x0B\x12\x1D\x0A\x19RESOURCE_FIELD_PROJECT_ID\x10\x15\x12\x15\x0A\x11RESOURCE_FIELD_ID\x10\x1FB\xEA\x01\x0A\x1Dcom.cbws.iam.options.v1alpha1B\x0COptionsProtoP\x01Z8go.cbws.cloud/protobufs/gen/go/cbws/iam/options/v1alpha1\xA2\x02\x03CIO\xAA\x02\x19Cbws.Iam.Options.V1alpha1\xCA\x02\x1ECbws\\Grpc\\Iam\\Options\\V1alpha1\xE2\x02\x1CGPBMetadata\\Cbws\\Iam\\Options\xEA\x02\x1CCbws::Iam::Options::V1alpha1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

