<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/virtual_machines/affinity/v1alpha1/affinity.proto

namespace Cbws\VirtualMachines\Grpc\Affinity\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.
 *
 * Generated from protobuf message <code>cbws.virtual_machines.affinity.v1alpha1.LabelSelector</code>
 */
class LabelSelector extends \Google\Protobuf\Internal\Message
{
    /**
     * matchExpressions is a list of label selector requirements. The requirements are ANDed.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.affinity.v1alpha1.LabelSelectorRequirement match_expressions = 1;</code>
     */
    protected $match_expressions = null;
    /**
     * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
     *
     * Generated from protobuf field <code>map<string, string> match_labels = 2;</code>
     */
    private $match_labels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\LabelSelectorRequirement $match_expressions
     *           matchExpressions is a list of label selector requirements. The requirements are ANDed.
     *     @type array|\Google\Protobuf\Internal\MapField $match_labels
     *           matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\Metadata\Affinity::initOnce();
        parent::__construct($data);
    }

    /**
     * matchExpressions is a list of label selector requirements. The requirements are ANDed.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.affinity.v1alpha1.LabelSelectorRequirement match_expressions = 1;</code>
     * @return \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\LabelSelectorRequirement
     */
    public function getMatchExpressions()
    {
        return $this->match_expressions;
    }

    /**
     * matchExpressions is a list of label selector requirements. The requirements are ANDed.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.affinity.v1alpha1.LabelSelectorRequirement match_expressions = 1;</code>
     * @param \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\LabelSelectorRequirement $var
     * @return $this
     */
    public function setMatchExpressions($var)
    {
        GPBUtil::checkMessage($var, \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\LabelSelectorRequirement::class);
        $this->match_expressions = $var;

        return $this;
    }

    /**
     * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
     *
     * Generated from protobuf field <code>map<string, string> match_labels = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMatchLabels()
    {
        return $this->match_labels;
    }

    /**
     * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
     *
     * Generated from protobuf field <code>map<string, string> match_labels = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMatchLabels($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->match_labels = $arr;

        return $this;
    }

}

