<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/virtual_machines/affinity/v1alpha1/affinity.proto

namespace Cbws\VirtualMachines\Grpc\Affinity\V1alpha1;

if (false) {
    /**
     * This class is deprecated. Use Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\LabelSelectorRequirement\Operator instead.
     * @deprecated
     */
    class LabelSelectorRequirement_Operator {}
}
class_exists(LabelSelectorRequirement\Operator::class);
@trigger_error('Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\LabelSelectorRequirement_Operator is deprecated and will be removed in the next major release. Use Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\LabelSelectorRequirement\Operator instead', E_USER_DEPRECATED);

