<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/virtual_machines/affinity/v1alpha1/affinity.proto

namespace Cbws\VirtualMachines\Grpc\Affinity\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.
 *
 * Generated from protobuf message <code>cbws.virtual_machines.affinity.v1alpha1.NodeSelector</code>
 */
class NodeSelector extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of node selector terms. The terms are ORed.
     *
     * Generated from protobuf field <code>repeated .cbws.virtual_machines.affinity.v1alpha1.NodeSelectorTerm node_selector_terms = 1;</code>
     */
    private $node_selector_terms;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\NodeSelectorTerm[]|\Google\Protobuf\Internal\RepeatedField $node_selector_terms
     *           A list of node selector terms. The terms are ORed.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\Metadata\Affinity::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of node selector terms. The terms are ORed.
     *
     * Generated from protobuf field <code>repeated .cbws.virtual_machines.affinity.v1alpha1.NodeSelectorTerm node_selector_terms = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNodeSelectorTerms()
    {
        return $this->node_selector_terms;
    }

    /**
     * A list of node selector terms. The terms are ORed.
     *
     * Generated from protobuf field <code>repeated .cbws.virtual_machines.affinity.v1alpha1.NodeSelectorTerm node_selector_terms = 1;</code>
     * @param \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\NodeSelectorTerm[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNodeSelectorTerms($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\NodeSelectorTerm::class);
        $this->node_selector_terms = $arr;

        return $this;
    }

}

