<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/virtual_machines/affinity/v1alpha1/affinity.proto

namespace Cbws\VirtualMachines\Grpc\Affinity\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it's a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).
 *
 * Generated from protobuf message <code>cbws.virtual_machines.affinity.v1alpha1.PreferredSchedulingTerm</code>
 */
class PreferredSchedulingTerm extends \Google\Protobuf\Internal\Message
{
    /**
     * A node selector term, associated with the corresponding weight.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.affinity.v1alpha1.NodeSelectorTerm preference = 1;</code>
     */
    protected $preference = null;
    /**
     * Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
     *
     * Generated from protobuf field <code>int32 weight = 2;</code>
     */
    protected $weight = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\NodeSelectorTerm $preference
     *           A node selector term, associated with the corresponding weight.
     *     @type int $weight
     *           Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\Metadata\Affinity::initOnce();
        parent::__construct($data);
    }

    /**
     * A node selector term, associated with the corresponding weight.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.affinity.v1alpha1.NodeSelectorTerm preference = 1;</code>
     * @return \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\NodeSelectorTerm
     */
    public function getPreference()
    {
        return $this->preference;
    }

    /**
     * A node selector term, associated with the corresponding weight.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.affinity.v1alpha1.NodeSelectorTerm preference = 1;</code>
     * @param \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\NodeSelectorTerm $var
     * @return $this
     */
    public function setPreference($var)
    {
        GPBUtil::checkMessage($var, \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\NodeSelectorTerm::class);
        $this->preference = $var;

        return $this;
    }

    /**
     * Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
     *
     * Generated from protobuf field <code>int32 weight = 2;</code>
     * @return int
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
     *
     * Generated from protobuf field <code>int32 weight = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->weight = $var;

        return $this;
    }

}

