<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/virtual_machines/affinity/v1alpha1/affinity.proto

namespace Cbws\VirtualMachines\Grpc\Affinity\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The weights of all of the matched WeightedInstanceAffinityTerm fields are added per-node to find the most preferred node(s)
 *
 * Generated from protobuf message <code>cbws.virtual_machines.affinity.v1alpha1.WeightedInstanceAffinityTerm</code>
 */
class WeightedInstanceAffinityTerm extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. A instance affinity term, associated with the corresponding weight.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.affinity.v1alpha1.InstanceAffinityTerm instance_affinity_term = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $instance_affinity_term = null;
    /**
     * weight associated with matching the corresponding instanceAffinityTerm, in the range 1-100.
     *
     * Generated from protobuf field <code>int32 weight = 2;</code>
     */
    protected $weight = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\InstanceAffinityTerm $instance_affinity_term
     *           Required. A instance affinity term, associated with the corresponding weight.
     *     @type int $weight
     *           weight associated with matching the corresponding instanceAffinityTerm, in the range 1-100.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\Metadata\Affinity::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. A instance affinity term, associated with the corresponding weight.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.affinity.v1alpha1.InstanceAffinityTerm instance_affinity_term = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\InstanceAffinityTerm
     */
    public function getInstanceAffinityTerm()
    {
        return $this->instance_affinity_term;
    }

    /**
     * Required. A instance affinity term, associated with the corresponding weight.
     *
     * Generated from protobuf field <code>.cbws.virtual_machines.affinity.v1alpha1.InstanceAffinityTerm instance_affinity_term = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\InstanceAffinityTerm $var
     * @return $this
     */
    public function setInstanceAffinityTerm($var)
    {
        GPBUtil::checkMessage($var, \Cbws\VirtualMachines\Grpc\Affinity\V1alpha1\InstanceAffinityTerm::class);
        $this->instance_affinity_term = $var;

        return $this;
    }

    /**
     * weight associated with matching the corresponding instanceAffinityTerm, in the range 1-100.
     *
     * Generated from protobuf field <code>int32 weight = 2;</code>
     * @return int
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * weight associated with matching the corresponding instanceAffinityTerm, in the range 1-100.
     *
     * Generated from protobuf field <code>int32 weight = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->weight = $var;

        return $this;
    }

}

