<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/iam/policy/v1alpha1/request_response.proto

namespace Cbws\IAM\Policy\GRPC\V1alpha1\Metadata;

class RequestResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Cbws\IAM\Policy\GRPC\V1alpha1\Metadata\Policy::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aac040a2f636277732f69616d2f706f6c6963792f7631616c706861312f" .
            "726571756573745f726573706f6e73652e70726f746f1218636277732e69" .
            "616d2e706f6c6963792e7631616c706861311a1f676f6f676c652f617069" .
            "2f6669656c645f6265686176696f722e70726f746f1a19676f6f676c652f" .
            "6170692f7265736f757263652e70726f746f22660a10536574506f6c6963" .
            "7952657175657374121b0a087265736f757263651801200128094209e041" .
            "02fa41030a012a12350a06706f6c69637918022001280b32202e63627773" .
            "2e69616d2e706f6c6963792e7631616c706861312e506f6c6963794203e0" .
            "4102222f0a10476574506f6c69637952657175657374121b0a087265736f" .
            "757263651801200128094209e04102fa41030a012a224f0a165465737450" .
            "65726d697373696f6e7352657175657374121b0a087265736f7572636518" .
            "01200128094209e04102fa41030a012a12180a0b7065726d697373696f6e" .
            "731802200328094203e04102222e0a17546573745065726d697373696f6e" .
            "73526573706f6e736512130a0b7065726d697373696f6e73180120032809" .
            "4280015a356769746875622e636f6d2f636277732f676f2d636277732d67" .
            "7270632f636277732f69616d2f706f6c6963792f7631616c70686131ca02" .
            "1d436277735c49414d5c506f6c6963795c475250435c5631616c70686131" .
            "e20226436277735c49414d5c506f6c6963795c475250435c5631616c7068" .
            "61315c4d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

