<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/compute/v1alpha1/machine_type.proto

namespace GPBMetadata\Cbws\Compute;

class MachineType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAF\x04\x0A(cbws/compute/v1alpha1/machine_type.proto\x12\x15cbws.compute.v1alpha1\x1A\x19google/api/resource.proto\"\xF0\x01\x0A\x0BMachineType\x12\x17\x0A\x04name\x18\x01 \x01(\x09B\x03\xE0A\x03R\x04name\x12\x17\x0A\x04zone\x18\x03 \x01(\x09B\x03\xE0A\x03R\x04zone\x12\x15\x0A\x03cpu\x18\x04 \x01(\x05B\x03\xE0A\x03R\x03cpu\x12 \x0A\x09memory_mb\x18\x05 \x01(\x05B\x03\xE0A\x03R\x08memoryMb\x12/\x0A\x11ephemeral_disk_gb\x18\x06 \x01(\x05B\x03\xE0A\x03R\x0FephemeralDiskGb:E\xEAAB\x0A\x1Ecompute.cbws.cloud/MachineType\x12 zones/{zone}/machinesType/{name}B\xD5\x01\x0A\x19com.cbws.compute.v1alpha1B\x10MachineTypeProtoP\x01Z4go.cbws.cloud/protobufs/gen/go/cbws/compute/v1alpha1\xA2\x02\x03CCX\xAA\x02\x15Cbws.Compute.V1alpha1\xCA\x02\x1ACbws\\Grpc\\Compute\\V1alpha1\xE2\x02\x18GPBMetadata\\Cbws\\Compute\xEA\x02\x17Cbws::Compute::V1alpha1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

