<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/compute/v1alpha1/machine.proto

namespace Cbws\Grpc\Compute\V1alpha1\GPBMetadata;

class Machine
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x8B\x08\x0A#cbws/compute/v1alpha1/machine.proto\x12\x15cbws.compute.v1alpha1\x1A\x19google/api/resource.proto\"\xC7\x05\x0A\x07Machine\x12\x17\x0A\x04name\x18\x01 \x01(\x09B\x03\xE0A\x05R\x04name\x12\x1B\x0A\x06parent\x18\x02 \x01(\x09B\x03\xE0A\x05R\x06parent\x12\x17\x0A\x04type\x18\x03 \x01(\x09B\x03\xE0A\x05R\x04type\x12\x19\x0A\x05image\x18\x0A \x01(\x09B\x03\xE0A\x02R\x05image\x12\x1F\x0A\x08hostname\x18\x04 \x01(\x09B\x03\xE0A\x02R\x08hostname\x12\x1D\x0A\x07address\x18\x07 \x01(\x09B\x03\xE0A\x03R\x07address\x12\x1E\x0A\x08ssh_keys\x18\x09 \x03(\x09B\x03\xE0A\x05R\x07sshKeys\x12\x1F\x0A\x08userdata\x18\x10 \x01(\x09B\x03\xE0A\x05R\x08userdata\x12?\x0A\x05state\x18\x08 \x01(\x0E2\$.cbws.compute.v1alpha1.Machine.StateB\x03\xE0A\x03R\x05state\x12G\x0A\x06labels\x18\x0B \x03(\x0B2*.cbws.compute.v1alpha1.Machine.LabelsEntryB\x03\xE0A\x01R\x06labels\x1A9\x0A\x0BLabelsEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12\x14\x0A\x05value\x18\x02 \x01(\x09R\x05value:\x028\x01\"\xC6\x01\x0A\x05State\x12\x15\x0A\x11STATE_UNSPECIFIED\x10\x00\x12\x16\x0A\x12STATE_PROVISIONING\x10\x01\x12\x11\x0A\x0DSTATE_STAGING\x10\x02\x12\x11\x0A\x0DSTATE_RUNNING\x10\x03\x12\x12\x0A\x0ESTATE_STOPPING\x10\x04\x12\x14\x0A\x10STATE_SUSPENDING\x10\x05\x12\x13\x0A\x0FSTATE_SUSPENDED\x10\x06\x12\x13\x0A\x0FSTATE_REPAIRING\x10\x07\x12\x14\x0A\x10STATE_TERMINATED\x10\x08:C\xEAA@\x0A\x1Acompute.cbws.cloud/Machine\x12\"projects/{project}/machines/{name}B\xDF\x01\x0A\x19com.cbws.compute.v1alpha1B\x0CMachineProtoP\x01Z4go.cbws.cloud/protobufs/gen/go/cbws/compute/v1alpha1\xA2\x02\x03CCX\xAA\x02\x15Cbws.Compute.V1alpha1\xCA\x02\x1ACbws\\Grpc\\Compute\\V1alpha1\xE2\x02&Cbws\\Grpc\\Compute\\V1alpha1\\GPBMetadata\xEA\x02\x17Cbws::Compute::V1alpha1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

