<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/iam/v1alpha1/iam.proto

namespace Cbws\IAM\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.iam.v1alpha1.CreateServiceAccountRequest</code>
 */
class CreateServiceAccountRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $parent = '';
    /**
     * Required. The account id that is used to generate the service account
     * email address and a stable unique id. It is unique within a project,
     * must be 6-30 characters long, and match the regular expression
     * `[a-z]([-a-z0-9]*[a-z0-9])` to comply with RFC1035.
     *
     * Generated from protobuf field <code>string account_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $account_id = '';
    /**
     * The [ServiceAccount][google.iam.admin.v1.ServiceAccount] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.iam.v1alpha1.ServiceAccount service_account = 3;</code>
     */
    protected $service_account = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The resource name of the project associated with the service
     *           accounts, such as `projects/my-project-123`.
     *     @type string $account_id
     *           Required. The account id that is used to generate the service account
     *           email address and a stable unique id. It is unique within a project,
     *           must be 6-30 characters long, and match the regular expression
     *           `[a-z]([-a-z0-9]*[a-z0-9])` to comply with RFC1035.
     *     @type \Cbws\IAM\GRPC\V1alpha1\ServiceAccount $service_account
     *           The [ServiceAccount][google.iam.admin.v1.ServiceAccount] resource to
     *           create. Currently, only the following values are user assignable:
     *           `display_name` and `description`.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\IAM\GRPC\V1alpha1\Metadata\Iam::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The resource name of the project associated with the service
     * accounts, such as `projects/my-project-123`.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Required. The account id that is used to generate the service account
     * email address and a stable unique id. It is unique within a project,
     * must be 6-30 characters long, and match the regular expression
     * `[a-z]([-a-z0-9]*[a-z0-9])` to comply with RFC1035.
     *
     * Generated from protobuf field <code>string account_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return string
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     * Required. The account id that is used to generate the service account
     * email address and a stable unique id. It is unique within a project,
     * must be 6-30 characters long, and match the regular expression
     * `[a-z]([-a-z0-9]*[a-z0-9])` to comply with RFC1035.
     *
     * Generated from protobuf field <code>string account_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param string $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_id = $var;

        return $this;
    }

    /**
     * The [ServiceAccount][google.iam.admin.v1.ServiceAccount] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.iam.v1alpha1.ServiceAccount service_account = 3;</code>
     * @return \Cbws\IAM\GRPC\V1alpha1\ServiceAccount
     */
    public function getServiceAccount()
    {
        return $this->service_account;
    }

    /**
     * The [ServiceAccount][google.iam.admin.v1.ServiceAccount] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.iam.v1alpha1.ServiceAccount service_account = 3;</code>
     * @param \Cbws\IAM\GRPC\V1alpha1\ServiceAccount $var
     * @return $this
     */
    public function setServiceAccount($var)
    {
        GPBUtil::checkMessage($var, \Cbws\IAM\GRPC\V1alpha1\ServiceAccount::class);
        $this->service_account = $var;

        return $this;
    }

}

