<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/iam/v1alpha1/iam.proto

namespace Cbws\IAM\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The service account keys list request.
 *
 * Generated from protobuf message <code>cbws.iam.v1alpha1.ListServiceAccountKeysRequest</code>
 */
class ListServiceAccountKeysRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. The resource name of the service account in the following format:
     * `projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}`.
     * Using `-` as a wildcard for the `PROJECT_ID`, will infer the project from
     * the account. The `ACCOUNT` value can be the `email` address or the
     * `unique_id` of the service account.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $parent = '';
    /**
     * Filters the types of keys the user wants to include in the list
     * response. Duplicate key types are not allowed. If no key type
     * is provided, all keys are returned.
     *
     * Generated from protobuf field <code>repeated .cbws.iam.v1alpha1.ServiceAccountKeyType key_types = 2;</code>
     */
    private $key_types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. The resource name of the service account in the following format:
     *           `projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}`.
     *           Using `-` as a wildcard for the `PROJECT_ID`, will infer the project from
     *           the account. The `ACCOUNT` value can be the `email` address or the
     *           `unique_id` of the service account.
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $key_types
     *           Filters the types of keys the user wants to include in the list
     *           response. Duplicate key types are not allowed. If no key type
     *           is provided, all keys are returned.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\IAM\GRPC\V1alpha1\Metadata\Iam::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. The resource name of the service account in the following format:
     * `projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}`.
     * Using `-` as a wildcard for the `PROJECT_ID`, will infer the project from
     * the account. The `ACCOUNT` value can be the `email` address or the
     * `unique_id` of the service account.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. The resource name of the service account in the following format:
     * `projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}`.
     * Using `-` as a wildcard for the `PROJECT_ID`, will infer the project from
     * the account. The `ACCOUNT` value can be the `email` address or the
     * `unique_id` of the service account.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Filters the types of keys the user wants to include in the list
     * response. Duplicate key types are not allowed. If no key type
     * is provided, all keys are returned.
     *
     * Generated from protobuf field <code>repeated .cbws.iam.v1alpha1.ServiceAccountKeyType key_types = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeyTypes()
    {
        return $this->key_types;
    }

    /**
     * Filters the types of keys the user wants to include in the list
     * response. Duplicate key types are not allowed. If no key type
     * is provided, all keys are returned.
     *
     * Generated from protobuf field <code>repeated .cbws.iam.v1alpha1.ServiceAccountKeyType key_types = 2;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeyTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Cbws\IAM\GRPC\V1alpha1\ServiceAccountKeyType::class);
        $this->key_types = $arr;

        return $this;
    }

}

