<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/iam/v1alpha1/service_account.proto

namespace Cbws\IAM\GRPC\V1alpha1;

use UnexpectedValueException;

/**
 * Supported public key output formats.
 *
 * Protobuf type <code>cbws.iam.v1alpha1.ServiceAccountPublicKeyType</code>
 */
class ServiceAccountPublicKeyType
{
    /**
     * Unspecified. Returns nothing here.
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_UNSPECIFIED = 0;</code>
     */
    const SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_UNSPECIFIED = 0;
    /**
     * X509 PEM format.
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_X509_PEM_FILE = 1;</code>
     */
    const SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_X509_PEM_FILE = 1;
    /**
     * PKCS #8 public key.
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_PKCS8_PUBLIC_KEY = 2;</code>
     */
    const SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_PKCS8_PUBLIC_KEY = 2;

    private static $valueToName = [
        self::SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_UNSPECIFIED => 'SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_UNSPECIFIED',
        self::SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_X509_PEM_FILE => 'SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_X509_PEM_FILE',
        self::SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_PKCS8_PUBLIC_KEY => 'SERVICE_ACCOUNT_PUBLIC_KEY_TYPE_PKCS8_PUBLIC_KEY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

