<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/iam/v1alpha1/service_account.proto

namespace Cbws\IAM\GRPC\V1alpha1;

use UnexpectedValueException;

/**
 * Supported key algorithms.
 *
 * Protobuf type <code>cbws.iam.v1alpha1.ServiceAccountKeyAlgorithm</code>
 */
class ServiceAccountKeyAlgorithm
{
    /**
     * An unspecified key algorithm.
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_KEY_ALGORITHM_UNSPECIFIED = 0;</code>
     */
    const SERVICE_ACCOUNT_KEY_ALGORITHM_UNSPECIFIED = 0;
    /**
     * 1k RSA Key.
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_1024 = 1;</code>
     */
    const SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_1024 = 1;
    /**
     * 2k RSA Key.
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_2048 = 2;</code>
     */
    const SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_2048 = 2;
    /**
     * 4k RSA Key.
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_4096 = 3;</code>
     */
    const SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_4096 = 3;

    private static $valueToName = [
        self::SERVICE_ACCOUNT_KEY_ALGORITHM_UNSPECIFIED => 'SERVICE_ACCOUNT_KEY_ALGORITHM_UNSPECIFIED',
        self::SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_1024 => 'SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_1024',
        self::SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_2048 => 'SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_2048',
        self::SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_4096 => 'SERVICE_ACCOUNT_KEY_ALGORITHM_RSA_4096',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

