<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/iam/v1alpha1/service_account.proto

namespace Cbws\IAM\GRPC\V1alpha1;

use UnexpectedValueException;

/**
 * Supported private key output formats.
 *
 * Protobuf type <code>cbws.iam.v1alpha1.ServiceAccountPrivateKeyType</code>
 */
class ServiceAccountPrivateKeyType
{
    /**
     * Unspecified. Equivalent to `TYPE_CREDENTIALS_FILE`.
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_UNSPECIFIED = 0;</code>
     */
    const SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_UNSPECIFIED = 0;
    /**
     * PKCS12 format.
     * The password for the PKCS12 file is `notasecret`.
     * For more information, see https://tools.ietf.org/html/rfc7292.
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_PKCS12_FILE = 1;</code>
     */
    const SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_PKCS12_FILE = 1;
    /**
     * Credentials File format.
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_CREDENTIALS_FILE = 2;</code>
     */
    const SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_CREDENTIALS_FILE = 2;

    private static $valueToName = [
        self::SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_UNSPECIFIED => 'SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_UNSPECIFIED',
        self::SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_PKCS12_FILE => 'SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_PKCS12_FILE',
        self::SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_CREDENTIALS_FILE => 'SERVICE_ACCOUNT_PRIVATE_KEY_TYPE_CREDENTIALS_FILE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

