<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/iam/v1alpha1/service_account.proto

namespace Cbws\IAM\GRPC\V1alpha1;

use UnexpectedValueException;

/**
 * Protobuf type <code>cbws.iam.v1alpha1.ServiceAccountKeyType</code>
 */
class ServiceAccountKeyType
{
    /**
     * Unspecified key type. The presence of this in the
     * message will immediately result in an error.
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_KEY_TYPE_UNSPECIFIED = 0;</code>
     */
    const SERVICE_ACCOUNT_KEY_TYPE_UNSPECIFIED = 0;
    /**
     * User-managed keys (managed and rotated by the user).
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_KEY_TYPE_USER_MANAGED = 1;</code>
     */
    const SERVICE_ACCOUNT_KEY_TYPE_USER_MANAGED = 1;
    /**
     * System-managed keys (managed and rotated by Cloudbear).
     *
     * Generated from protobuf enum <code>SERVICE_ACCOUNT_KEY_TYPE_SYSTEM_MANAGED = 2;</code>
     */
    const SERVICE_ACCOUNT_KEY_TYPE_SYSTEM_MANAGED = 2;

    private static $valueToName = [
        self::SERVICE_ACCOUNT_KEY_TYPE_UNSPECIFIED => 'SERVICE_ACCOUNT_KEY_TYPE_UNSPECIFIED',
        self::SERVICE_ACCOUNT_KEY_TYPE_USER_MANAGED => 'SERVICE_ACCOUNT_KEY_TYPE_USER_MANAGED',
        self::SERVICE_ACCOUNT_KEY_TYPE_SYSTEM_MANAGED => 'SERVICE_ACCOUNT_KEY_TYPE_SYSTEM_MANAGED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

