<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/iam/v1alpha1/iam.proto

namespace Cbws\IAM\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.iam.v1alpha1.UpdateServiceAccountRequest</code>
 */
class UpdateServiceAccountRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The [ServiceAccount][google.iam.admin.v1.ServiceAccount] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.iam.v1alpha1.ServiceAccount service_account = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $service_account = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\IAM\GRPC\V1alpha1\ServiceAccount $service_account
     *           The [ServiceAccount][google.iam.admin.v1.ServiceAccount] resource to
     *           create. Currently, only the following values are user assignable:
     *           `display_name` and `description`.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\IAM\GRPC\V1alpha1\Metadata\Iam::initOnce();
        parent::__construct($data);
    }

    /**
     * The [ServiceAccount][google.iam.admin.v1.ServiceAccount] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.iam.v1alpha1.ServiceAccount service_account = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Cbws\IAM\GRPC\V1alpha1\ServiceAccount
     */
    public function getServiceAccount()
    {
        return $this->service_account;
    }

    /**
     * The [ServiceAccount][google.iam.admin.v1.ServiceAccount] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.iam.v1alpha1.ServiceAccount service_account = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Cbws\IAM\GRPC\V1alpha1\ServiceAccount $var
     * @return $this
     */
    public function setServiceAccount($var)
    {
        GPBUtil::checkMessage($var, \Cbws\IAM\GRPC\V1alpha1\ServiceAccount::class);
        $this->service_account = $var;

        return $this;
    }

}

