<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/projects/v1alpha1/projects.proto

namespace Cbws\Grpc\Projects\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The service account list request.
 *
 * Generated from protobuf message <code>cbws.projects.v1alpha1.ListProjectsRequest</code>
 */
class ListProjectsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Optional limit on the number of service accounts to include in the
     * response. Further accounts can subsequently be obtained by including the
     * [ListServiceAccountsResponse.next_page_token][google.iam.admin.v1.ListServiceAccountsResponse.next_page_token]
     * in a subsequent request.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize"];</code>
     */
    protected $page_size = 0;
    /**
     * Optional pagination token returned in an earlier
     * [ListServiceAccountsResponse.next_page_token][google.iam.admin.v1.ListServiceAccountsResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [json_name = "pageToken"];</code>
     */
    protected $page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $page_size
     *           Optional limit on the number of service accounts to include in the
     *           response. Further accounts can subsequently be obtained by including the
     *           [ListServiceAccountsResponse.next_page_token][google.iam.admin.v1.ListServiceAccountsResponse.next_page_token]
     *           in a subsequent request.
     *     @type string $page_token
     *           Optional pagination token returned in an earlier
     *           [ListServiceAccountsResponse.next_page_token][google.iam.admin.v1.ListServiceAccountsResponse.next_page_token].
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\Grpc\Projects\V1alpha1\GPBMetadata\Projects::initOnce();
        parent::__construct($data);
    }

    /**
     * Optional limit on the number of service accounts to include in the
     * response. Further accounts can subsequently be obtained by including the
     * [ListServiceAccountsResponse.next_page_token][google.iam.admin.v1.ListServiceAccountsResponse.next_page_token]
     * in a subsequent request.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize"];</code>
     * @return int
     */
    public function getPageSize()
    {
        return $this->page_size;
    }

    /**
     * Optional limit on the number of service accounts to include in the
     * response. Further accounts can subsequently be obtained by including the
     * [ListServiceAccountsResponse.next_page_token][google.iam.admin.v1.ListServiceAccountsResponse.next_page_token]
     * in a subsequent request.
     *
     * Generated from protobuf field <code>int32 page_size = 2 [json_name = "pageSize"];</code>
     * @param int $var
     * @return $this
     */
    public function setPageSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_size = $var;

        return $this;
    }

    /**
     * Optional pagination token returned in an earlier
     * [ListServiceAccountsResponse.next_page_token][google.iam.admin.v1.ListServiceAccountsResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [json_name = "pageToken"];</code>
     * @return string
     */
    public function getPageToken()
    {
        return $this->page_token;
    }

    /**
     * Optional pagination token returned in an earlier
     * [ListServiceAccountsResponse.next_page_token][google.iam.admin.v1.ListServiceAccountsResponse.next_page_token].
     *
     * Generated from protobuf field <code>string page_token = 3 [json_name = "pageToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->page_token = $var;

        return $this;
    }

}

