<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/projects/v1alpha1/projects.proto

namespace Cbws\Grpc\Projects\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.projects.v1alpha1.ListProjectsResponse</code>
 */
class ListProjectsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .cbws.projects.v1alpha1.Project projects = 1 [json_name = "projects"];</code>
     */
    private $projects;
    /**
     * To retrieve the next page of results, set
     * [ListServiceAccountsRequest.page_token][google.iam.admin.v1.ListServiceAccountsRequest.page_token]
     * to this value.
     *
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Cbws\Grpc\Projects\V1alpha1\Project>|\Google\Protobuf\Internal\RepeatedField $projects
     *     @type string $next_page_token
     *           To retrieve the next page of results, set
     *           [ListServiceAccountsRequest.page_token][google.iam.admin.v1.ListServiceAccountsRequest.page_token]
     *           to this value.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cbws\Projects\Projects::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .cbws.projects.v1alpha1.Project projects = 1 [json_name = "projects"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProjects()
    {
        return $this->projects;
    }

    /**
     * Generated from protobuf field <code>repeated .cbws.projects.v1alpha1.Project projects = 1 [json_name = "projects"];</code>
     * @param array<\Cbws\Grpc\Projects\V1alpha1\Project>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProjects($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cbws\Grpc\Projects\V1alpha1\Project::class);
        $this->projects = $arr;

        return $this;
    }

    /**
     * To retrieve the next page of results, set
     * [ListServiceAccountsRequest.page_token][google.iam.admin.v1.ListServiceAccountsRequest.page_token]
     * to this value.
     *
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * To retrieve the next page of results, set
     * [ListServiceAccountsRequest.page_token][google.iam.admin.v1.ListServiceAccountsRequest.page_token]
     * to this value.
     *
     * Generated from protobuf field <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

