<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/projects/v1alpha1/projects.proto

namespace Cbws\Projects\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.projects.v1alpha1.DeleteProjectMetadata</code>
 */
class DeleteProjectMetadata extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\Projects\GRPC\V1alpha1\Metadata\Projects::initOnce();
        parent::__construct($data);
    }

}

