<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/projects/v1alpha1/projects.proto

namespace Cbws\Projects\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.projects.v1alpha1.UpdateProjectRequest</code>
 */
class UpdateProjectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The project to update.
     * The project's `name` field is used to identify the project to be updated.
     * Format: projects/{project}
     *
     * Generated from protobuf field <code>.cbws.projects.v1alpha1.Project project = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $project = null;
    /**
     * The list of fields to be updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     */
    protected $update_mask = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\Projects\GRPC\V1alpha1\Project $project
     *           The project to update.
     *           The project's `name` field is used to identify the project to be updated.
     *           Format: projects/{project}
     *     @type \Google\Protobuf\FieldMask $update_mask
     *           The list of fields to be updated.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\Projects\GRPC\V1alpha1\Metadata\Projects::initOnce();
        parent::__construct($data);
    }

    /**
     * The project to update.
     * The project's `name` field is used to identify the project to be updated.
     * Format: projects/{project}
     *
     * Generated from protobuf field <code>.cbws.projects.v1alpha1.Project project = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Cbws\Projects\GRPC\V1alpha1\Project
     */
    public function getProject()
    {
        return $this->project;
    }

    /**
     * The project to update.
     * The project's `name` field is used to identify the project to be updated.
     * Format: projects/{project}
     *
     * Generated from protobuf field <code>.cbws.projects.v1alpha1.Project project = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Cbws\Projects\GRPC\V1alpha1\Project $var
     * @return $this
     */
    public function setProject($var)
    {
        GPBUtil::checkMessage($var, \Cbws\Projects\GRPC\V1alpha1\Project::class);
        $this->project = $var;

        return $this;
    }

    /**
     * The list of fields to be updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @return \Google\Protobuf\FieldMask
     */
    public function getUpdateMask()
    {
        return $this->update_mask;
    }

    /**
     * The list of fields to be updated.
     *
     * Generated from protobuf field <code>.google.protobuf.FieldMask update_mask = 2;</code>
     * @param \Google\Protobuf\FieldMask $var
     * @return $this
     */
    public function setUpdateMask($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\FieldMask::class);
        $this->update_mask = $var;

        return $this;
    }

}

