<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/logging/v1alpha1/log.proto

namespace Cbws\Logging\Grpc\V1alpha1\Metadata;

class Log
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Cbws\Grpc\V1alpha1\Metadata\MonitoredResource::initOnce();
        \Cbws\IAM\Options\GRPC\V1alpha1\Metadata\Options::initOnce();
        \Cbws\Logging\Grpc\V1alpha1\Metadata\HttpRequest::initOnce();
        \Cbws\Logging\Grpc\V1alpha1\Metadata\LogSeverity::initOnce();
        \Cbws\Projects\GRPC\V1alpha1\Metadata\Project::initOnce();
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\Client::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Api\Resource::initOnce();
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \GPBMetadata\Google\Protobuf\Duration::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Struct::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Google\Longrunning\Operations::initOnce();
        \GPBMetadata\Google\Protobuf\FieldMask::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9d070a1f636277732f6c6f6767696e672f7631616c706861312f6c6f672e70726f746f1215636277732e6c6f6767696e672e7631616c706861311a27636277732f69616d2f6f7074696f6e732f7631616c706861312f6f7074696f6e732e70726f746f1a28636277732f6c6f6767696e672f7631616c706861312f687474705f726571756573742e70726f746f1a28636277732f6c6f6767696e672f7631616c706861312f6c6f675f73657665726974792e70726f746f1a24636277732f70726f6a656374732f7631616c706861312f70726f6a6563742e70726f746f1a1c676f6f676c652f6170692f616e6e6f746174696f6e732e70726f746f1a17676f6f676c652f6170692f636c69656e742e70726f746f1a1f676f6f676c652f6170692f6669656c645f6265686176696f722e70726f746f1a19676f6f676c652f6170692f7265736f757263652e70726f746f1a19676f6f676c652f70726f746f6275662f616e792e70726f746f1a1e676f6f676c652f70726f746f6275662f6475726174696f6e2e70726f746f1a1b676f6f676c652f70726f746f6275662f656d7074792e70726f746f1a1c676f6f676c652f70726f746f6275662f7374727563742e70726f746f1a1f676f6f676c652f70726f746f6275662f74696d657374616d702e70726f746f1a23676f6f676c652f6c6f6e6772756e6e696e672f6f7065726174696f6e732e70726f746f1a20676f6f676c652f70726f746f6275662f6669656c645f6d61736b2e70726f746f22ed010a034c6f6712130a06706172656e741801200128094203e0410212110a046e616d651802200128094203e041023abd01ea41b9010a1a6c6f6767696e672e676f6f676c65617069732e636f6d2f4c6f67121d70726f6a656374732f7b70726f6a6563747d2f6c6f67732f7b6c6f677d12276f7267616e697a6174696f6e732f7b6f7267616e697a6174696f6e7d2f6c6f67732f7b6c6f677d121b666f6c646572732f7b666f6c6465727d2f6c6f67732f7b6c6f677d122c62696c6c696e674163636f756e74732f7b62696c6c696e675f6163636f756e747d2f6c6f67732f7b6c6f677d1a086c6f675f6e616d6542775a326769746875622e636f6d2f636277732f676f2d636277732d677270632f636277732f6c6f6767696e672f7631616c70686131ca021a436277735c4c6f6767696e675c477270635c5631616c70686131e20223436277735c4c6f6767696e675c477270635c5631616c706861315c4d65746164617461620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

