<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/longrunning/v1alpha1/operations.proto

namespace Cbws\LongRunning\Grpc\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message for [Operations.CancelOperation][google.longrunning.Operations.CancelOperation].
 *
 * Generated from protobuf message <code>cbws.longrunning.v1alpha1.CancelOperationRequest</code>
 */
class CancelOperationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the operation resource to be cancelled.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the operation resource to be cancelled.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\LongRunning\Grpc\V1alpha1\Metadata\Operations::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the operation resource to be cancelled.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the operation resource to be cancelled.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

