<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/vpn/v1alpha1/vpn.proto

namespace Cbws\VPN\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.vpn.v1alpha1.UpdateProfileRequest</code>
 */
class UpdateProfileRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The [Profile][cbws.vpn.v1alpha1.Instance] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.vpn.v1alpha1.Profile profile = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $profile = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\VPN\GRPC\V1alpha1\Profile $profile
     *           The [Profile][cbws.vpn.v1alpha1.Instance] resource to
     *           create. Currently, only the following values are user assignable:
     *           `display_name` and `description`.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\VPN\GRPC\V1alpha1\Metadata\Vpn::initOnce();
        parent::__construct($data);
    }

    /**
     * The [Profile][cbws.vpn.v1alpha1.Instance] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.vpn.v1alpha1.Profile profile = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Cbws\VPN\GRPC\V1alpha1\Profile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * The [Profile][cbws.vpn.v1alpha1.Instance] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.vpn.v1alpha1.Profile profile = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Cbws\VPN\GRPC\V1alpha1\Profile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Cbws\VPN\GRPC\V1alpha1\Profile::class);
        $this->profile = $var;

        return $this;
    }

}

