<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cbws/vpn/v1alpha1/vpn.proto

namespace Cbws\VPN\GRPC\V1alpha1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cbws.vpn.v1alpha1.UpdateInstanceRequest</code>
 */
class UpdateInstanceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The [Instance][cbws.vpn.v1alpha1.Instance] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.vpn.v1alpha1.Instance instance = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $instance = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cbws\VPN\GRPC\V1alpha1\Instance $instance
     *           The [Instance][cbws.vpn.v1alpha1.Instance] resource to
     *           create. Currently, only the following values are user assignable:
     *           `display_name` and `description`.
     * }
     */
    public function __construct($data = NULL) {
        \Cbws\VPN\GRPC\V1alpha1\Metadata\Vpn::initOnce();
        parent::__construct($data);
    }

    /**
     * The [Instance][cbws.vpn.v1alpha1.Instance] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.vpn.v1alpha1.Instance instance = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Cbws\VPN\GRPC\V1alpha1\Instance
     */
    public function getInstance()
    {
        return $this->instance;
    }

    /**
     * The [Instance][cbws.vpn.v1alpha1.Instance] resource to
     * create. Currently, only the following values are user assignable:
     * `display_name` and `description`.
     *
     * Generated from protobuf field <code>.cbws.vpn.v1alpha1.Instance instance = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Cbws\VPN\GRPC\V1alpha1\Instance $var
     * @return $this
     */
    public function setInstance($var)
    {
        GPBUtil::checkMessage($var, \Cbws\VPN\GRPC\V1alpha1\Instance::class);
        $this->instance = $var;

        return $this;
    }

}

