on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: get-version
        run: |
          version=${GITHUB_REF:11}
          echo "::set-output name=version::$version"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }} # Using Personal Access Token to resolve the issue mentioned in https://github.com/actions/create-release/issues/52
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{steps.get-version.outputs.version}}
          draft: false
          prerelease: true
