<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cbws/iam/policy/v1alpha1/policy.proto

namespace GPBMetadata\Cbws\Iam\Policy;

class Policy
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE2\x03\x0A%cbws/iam/policy/v1alpha1/policy.proto\x12\x18cbws.iam.policy.v1alpha1\"[\x0A\x06Policy\x12=\x0A\x08bindings\x18\x04 \x03(\x0B2!.cbws.iam.policy.v1alpha1.BindingR\x08bindings\x12\x12\x0A\x04etag\x18\x03 \x01(\x0CR\x04etag\"Y\x0A\x07Binding\x12\x12\x0A\x04role\x18\x01 \x01(\x09R\x04role\x12 \x0A\x0Bdescription\x18\x03 \x01(\x09R\x0Bdescription\x12\x18\x0A\x07members\x18\x02 \x03(\x09R\x07membersB\xDE\x01\x0A\x1Ccom.cbws.iam.policy.v1alpha1B\x0BPolicyProtoP\x01Z7go.cbws.cloud/protobufs/gen/go/cbws/iam/policy/v1alpha1\xA2\x02\x03CIP\xAA\x02\x18Cbws.Iam.Policy.V1alpha1\xCA\x02\x18Cbws\\Iam\\Policy\\V1alpha1\xE2\x02\x1BGPBMetadata\\Cbws\\Iam\\Policy\xEA\x02\x1BCbws::Iam::Policy::V1alpha1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

